services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - kafka-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    ports:
      - "9092:9092"
    restart: always
    networks:
      - kafka-network

  postgres-auth-service:
    image: postgres:latest
    container_name: postgres-auth-service
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: viraj179
      POSTGRES_DB: auth-service
    ports:
      - "5431:5432"
    networks:
      - kafka-network

  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    ports:
      - "9000:4000"
    depends_on:
      - kafka
      - postgres-auth-service
    environment:
      KAFKA_BROKER: kafka:9092
      NODE_ENV: development
      DB_HOST: postgres-auth-service
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: viraj179
      DB_NAME: auth-service
    networks:
      - kafka-network

  postgres-user-management:
    image: postgres:latest
    container_name: postgres-user-management
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: viraj179
      POSTGRES_DB: user-management
    ports:
      - "5433:5432"
    networks:
      - kafka-network

  user-management-service:
    build:
      context: ./user-management
    container_name: user-management
    ports:
      - "9010:4001"
    depends_on:
      - kafka
      - postgres-user-management
    environment:
      KAFKA_BROKER: kafka:9092
      NODE_ENV: development
      DB_HOST: postgres-user-management
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: viraj179
      DB_NAME: user_management
    networks:
      - kafka-network

networks:
  kafka-network:
    driver: bridge
