services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - kafka-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    ports:
      - "9092:9092"
    restart: always

    networks:
      - kafka-network

  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    ports:
      - "4000:4000"
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: kafka:9092
      NODE_ENV: development
    networks:
      - kafka-network

  user-management-service:
    build:
      context: ./user-management
    container_name: user-management
    ports:
      - "4001:4001"
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: kafka:9092
      NODE_ENV: development
    networks:
      - kafka-network

  networks:
  kafka-network:
    driver: bridge
